Changes in has_key in python3
I ran the code and found the above changes for python3, has_key is replaced with __contains__ or you can use in operator instead of it.
The error was AttributeError: 'dict' object has no attribute 'has_key'